"""initial_schema_with_subject

Revision ID: 7add1ee22e86
Revises: 
Create Date: 2026-07-21 18:55:50.352102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7add1ee22e86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('classes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_classes_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes'))
    )
    op.create_index(op.f('ix_classes_department_id'), 'classes', ['department_id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_subjects_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('department_id', 'name', name='uq_subject_department_name'),
    sa.UniqueConstraint('department_id', 'subject_code', name='uq_subject_department_code')
    )
    op.create_index(op.f('ix_subjects_department_id'), 'subjects', ['department_id'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_index(op.f('ix_subjects_subject_code'), 'subjects', ['subject_code'], unique=False)
    op.create_table('exams',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exams_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_exams_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    op.create_index(op.f('ix_exams_created_by'), 'exams', ['created_by'], unique=False)
    op.create_index(op.f('ix_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_index(op.f('ix_exams_title'), 'exams', ['title'], unique=False)
    op.create_table('students',
    sa.Column('roll_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_students_class_id_classes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_table('exam_schedules',
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='examschedulestatus'), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_schedules_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_schedules'))
    )
    op.create_index(op.f('ix_exam_schedules_exam_id'), 'exam_schedules', ['exam_id'], unique=False)
    op.create_table('questions',
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('negative_marks', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_questions_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_table('exam_sessions',
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUBMITTED', 'EXPIRED', 'TERMINATED', name='sessionstatus'), nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('is_auto_submitted', sa.Boolean(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('exam_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_schedule_id'], ['exam_schedules.id'], name=op.f('fk_exam_sessions_exam_schedule_id_exam_schedules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_exam_sessions_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_sessions')),
    sa.UniqueConstraint('student_id', 'exam_schedule_id', name='uq_student_exam_session')
    )
    op.create_index(op.f('ix_exam_sessions_exam_schedule_id'), 'exam_sessions', ['exam_schedule_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_student_id'), 'exam_sessions', ['student_id'], unique=False)
    op.create_table('options',
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_options'))
    )
    op.create_index(op.f('ix_options_question_id'), 'options', ['question_id'], unique=False)
    op.create_table('student_exams',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('exam_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_schedule_id'], ['exam_schedules.id'], name=op.f('fk_student_exams_exam_schedule_id_exam_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_exams_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_exams')),
    sa.UniqueConstraint('student_id', 'exam_schedule_id', name='uq_student_exam_schedule')
    )
    op.create_index(op.f('ix_student_exams_exam_schedule_id'), 'student_exams', ['exam_schedule_id'], unique=False)
    op.create_index(op.f('ix_student_exams_student_id'), 'student_exams', ['student_id'], unique=False)
    op.create_table('results',
    sa.Column('obtained_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exam_session_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], name=op.f('fk_results_exam_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    op.create_index(op.f('ix_results_exam_session_id'), 'results', ['exam_session_id'], unique=True)
    op.create_table('student_answers',
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exam_session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], name=op.f('fk_student_answers_exam_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_student_answers_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['options.id'], name=op.f('fk_student_answers_selected_option_id_options'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_answers')),
    sa.UniqueConstraint('exam_session_id', 'question_id', name='uq_session_question_answer')
    )
    op.create_index(op.f('ix_student_answers_exam_session_id'), 'student_answers', ['exam_session_id'], unique=False)
    op.create_index(op.f('ix_student_answers_question_id'), 'student_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_answers_selected_option_id'), 'student_answers', ['selected_option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_answers_selected_option_id'), table_name='student_answers')
    op.drop_index(op.f('ix_student_answers_question_id'), table_name='student_answers')
    op.drop_index(op.f('ix_student_answers_exam_session_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index(op.f('ix_results_exam_session_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_student_exams_student_id'), table_name='student_exams')
    op.drop_index(op.f('ix_student_exams_exam_schedule_id'), table_name='student_exams')
    op.drop_table('student_exams')
    op.drop_index(op.f('ix_options_question_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_exam_sessions_student_id'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_exam_schedule_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exam_schedules_exam_id'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_exams_title'), table_name='exams')
    op.drop_index(op.f('ix_exams_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_created_by'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_subjects_subject_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_department_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_department_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
