"""remove_title_and_description_from_exam

Revision ID: 501f418bfaa4
Revises: 7add1ee22e86
Create Date: 2026-07-21 19:04:27.112060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501f418bfaa4'
down_revision: Union[str, Sequence[str], None] = '7add1ee22e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_title'), table_name='exams')
    op.drop_column('exams', 'description')
    op.drop_column('exams', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_exams_title'), 'exams', ['title'], unique=False)
    # ### end Alembic commands ###
