"""add password and is_active to student

Revision ID: dc4b831858c5
Revises: 581f55c0f423
Create Date: 2026-07-21 20:35:46.582562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4b831858c5'
down_revision: Union[str, Sequence[str], None] = '581f55c0f423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'password_hash')
    # ### end Alembic commands ###
