#!/bin/sh
set -e
lb config noauto \
    --distribution trixie \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --debian-installer live \
    --debian-installer-gui true \
    --debian-installer-preseedfile preseed.cfg \
    "${@}"

